#!/bin/bash

echo "please  enter your username::" # text added here will be added to the variable

read -s  USERNAME

echo "username entered: $USERNAME"
echo "please  enter your password::" # text added here will be added to the variable

read  -s PASSWORD

